config/routes.rb
Rails.application.routes.draw do
  root 'finalpage#start'

  resources :largesurveys

  resources :midsurveys

  get 'finalpage/direct', as: "final"

  resources :smallsurveys

end

app/models/largesurvey.rb
class Largesurvey < ActiveRecord::Base
	validates :name, :review, presence:true
	validate :large_input
	def large_input
		input_length = review.lstrip.rstrip.split(" ").length
		errors.add(:review, 'Your input length must between 135 to 145 words') if 
			(input_length < 135 or input_length > 145)
	end
		
	def self.to_csv
	  CSV.generate do |csv|
	    csv << column_names
	    all.each do |message|
	      csv << message.attributes.values_at(*column_names)
	    end
	  end
	end
end

app/models/midsurvey.rb
class Midsurvey < ActiveRecord::Base
	validates :name, :review, presence:true
	validate :mid_input
	def mid_input
		input_length = review.lstrip.rstrip.split(" ").length
		errors.add(:review, 'Your input length must between 40 to 50 words') if 
			(input_length < 40 or input_length > 50)
	end
		
	def self.to_csv
	  CSV.generate do |csv|
	    csv << column_names
	    all.each do |message|
	      csv << message.attributes.values_at(*column_names)
	    end
	  end
	end
end

app/models/smallsurvey.rb
class Smallsurvey < ActiveRecord::Base
	validates :name, :review, presence:true
	validate :small_input
	def small_input
		input_length = review.lstrip.rstrip.split(" ").length
		errors.add(:review, 'Your input length must between 10 to 20 words') if 
			(input_length < 10 or input_length > 20)
	end
		
	def self.to_csv
	  CSV.generate do |csv|
	    csv << column_names
	    all.each do |message|
	      csv << message.attributes.values_at(*column_names)
	    end
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finalpage_controller.rb
class FinalpageController < ApplicationController
  def direct
  end
  def start
  end
end

app/controllers/largesurveys_controller.rb
class LargesurveysController < ApplicationController
  before_action :set_largesurvey, only: [:show, :edit, :update, :destroy]

  # GET /largesurveys
  # GET /largesurveys.json
  def index
    @largesurveys = Largesurvey.all
    respond_to do |format|
      format.html
      format.csv { send_data @largesurveys.to_csv }
    end
  end

  # GET /largesurveys/1
  # GET /largesurveys/1.json
  def show
  end

  # GET /largesurveys/new
  def new
    @largesurvey = Largesurvey.new
  end

  # GET /largesurveys/1/edit
  def edit
  end

  # POST /largesurveys
  # POST /largesurveys.json
  def create
    @largesurvey = Largesurvey.new(largesurvey_params)

    respond_to do |format|
      if @largesurvey.save
        format.html { redirect_to final_path, notice: 'Largesurvey was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /largesurveys/1
  # PATCH/PUT /largesurveys/1.json
  def update
    respond_to do |format|
      if @largesurvey.update(largesurvey_params)
        format.html { redirect_to @largesurvey, notice: 'Largesurvey was successfully updated.' }
        format.json { render :show, status: :ok, location: @largesurvey }
      else
        format.html { render :edit }
        format.json { render json: @largesurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /largesurveys/1
  # DELETE /largesurveys/1.json
  def destroy
    @largesurvey.destroy
    respond_to do |format|
      format.html { redirect_to largesurveys_url, notice: 'Largesurvey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_largesurvey
      @largesurvey = Largesurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def largesurvey_params
      params.require(:largesurvey).permit(:name, :review)
    end
end

app/controllers/midsurveys_controller.rb
class MidsurveysController < ApplicationController
  before_action :set_midsurvey, only: [:show, :edit, :update, :destroy]

  # GET /midsurveys
  # GET /midsurveys.json
  def index
    @midsurveys = Midsurvey.all
    respond_to do |format|
      format.html
      format.csv { send_data @midsurveys.to_csv }
    end
  end

  # GET /midsurveys/1
  # GET /midsurveys/1.json
  def show
  end

  # GET /midsurveys/new
  def new
    @midsurvey = Midsurvey.new
  end

  # GET /midsurveys/1/edit
  def edit
  end

  # POST /midsurveys
  # POST /midsurveys.json
  def create
    @midsurvey = Midsurvey.new(midsurvey_params)

    respond_to do |format|
      if @midsurvey.save
        format.html { redirect_to final_path, notice: 'Midsurvey was successfully created.' }
        format.json { render :show, status: :created, location: @midsurvey }
      else
        format.html { render :new }
        format.json { render json: @midsurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midsurveys/1
  # PATCH/PUT /midsurveys/1.json
  def update
    respond_to do |format|
      if @midsurvey.update(midsurvey_params)
        format.html { redirect_to @midsurvey, notice: 'Midsurvey was successfully updated.' }
        format.json { render :show, status: :ok, location: @midsurvey }
      else
        format.html { render :edit }
        format.json { render json: @midsurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midsurveys/1
  # DELETE /midsurveys/1.json
  def destroy
    @midsurvey.destroy
    respond_to do |format|
      format.html { redirect_to midsurveys_url, notice: 'Midsurvey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midsurvey
      @midsurvey = Midsurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midsurvey_params
      params.require(:midsurvey).permit(:name, :review)
    end
end

app/controllers/smallsurveys_controller.rb
class SmallsurveysController < ApplicationController
  before_action :set_smallsurvey, only: [:show, :edit, :update, :destroy]

  # GET /smallsurveys
  # GET /smallsurveys.json
  def index
    @smallsurveys = Smallsurvey.all
    respond_to do |format|
      format.html
      format.csv { send_data @smallsurveys.to_csv }
    end
  end

  # GET /smallsurveys/1
  # GET /smallsurveys/1.json
  def show
    respond_to do |format|
      format.html
      
    end
  end

  # GET /smallsurveys/new
  def new
    @smallsurvey = Smallsurvey.new
  end

  # GET /smallsurveys/1/edit
  def edit
  end

  # POST /smallsurveys
  # POST /smallsurveys.json
  def create
    @smallsurvey = Smallsurvey.new(smallsurvey_params)

    respond_to do |format|
      if @smallsurvey.save
        format.html { redirect_to final_path, notice: 'Smallsurvey was successfully created.' }
        format.json { render :show, status: :created, location: @smallsurvey }
      else
        format.html { render :new }
        format.json { render json: @smallsurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smallsurveys/1
  # PATCH/PUT /smallsurveys/1.json
  def update
    respond_to do |format|
      if @smallsurvey.update(smallsurvey_params)
        format.html { redirect_to @smallsurvey, notice: 'Smallsurvey was successfully updated.' }
        format.json { render :show, status: :ok, location: @smallsurvey }
      else
        format.html { render :edit }
        format.json { render json: @smallsurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smallsurveys/1
  # DELETE /smallsurveys/1.json
  def destroy
    @smallsurvey.destroy
    respond_to do |format|
      format.html { redirect_to smallsurveys_url, notice: 'Smallsurvey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smallsurvey
      @smallsurvey = Smallsurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smallsurvey_params
      params.require(:smallsurvey).permit(:name, :review)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finalpage_helper.rb
module FinalpageHelper
end

app/helpers/largesurveys_helper.rb
module LargesurveysHelper
end

app/helpers/midsurveys_helper.rb
module MidsurveysHelper
end

app/helpers/samllsurveys_helper.rb
module SamllsurveysHelper
end

app/helpers/smallsurveys_helper.rb
module SmallsurveysHelper
end

app/views/finalpage/direct.html.haml
%br
%br

%div{:class => "text-center text-success"}
	%h4 Thank you for submitting your restaurant review. 
	%h4 Next, please click on the link below to answer a few additional questions about the restaurant experience you have just described.
	%a{:href => "https://columbia.az1.qualtrics.com/SE/?SID=SV_ehRIIvtDXOwdx8V"}https://columbia.az1.qualtrics.com/SE/?SID=SV_ehRIIvtDXOwdx8V

app/views/finalpage/start.html.haml
.col
	%br
	%br
	= link_to "10-20 words surveys CSV", smallsurveys_path
	%br
	= link_to "40-50 words surveys CSV", midsurveys_path
	%br
	= link_to "135-145 words surveys CSV", largesurveys_path
.col
	%br
	%br
	=link_to "new 10-20 words survey", new_smallsurvey_path
	%br

	=link_to "new 40-50 words survey", new_midsurvey_path
	%br

	=link_to "new 135-145 words survey", new_largesurvey_path

app/views/largesurveys/_form.html.haml
= form_for @largesurvey do |f|
  - if @largesurvey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@largesurvey.errors.count, "error")} prohibited this largesurvey from being saved:"
      %ul
        - @largesurvey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :review
    = f.text_field :review
  .actions
    = f.submit 'Save'

app/views/largesurveys/edit.html.haml
%h1 Editing largesurvey

= render 'form'

= link_to 'Show', @largesurvey
\|
= link_to 'Back', largesurveys_path

app/views/largesurveys/index.html.haml
%h3 All the surveys between 135-145 words 
%br
Download:
= link_to "CSV", largesurveys_path(format: "csv")
%br
%br

%table{:class => "table table-hover"}
  %tr
    %th Name
    %th Review
    %th
    %th
    %th

  - @largesurveys.each do |largesurvey|
    %tr
      %td= largesurvey.name
      %td= largesurvey.review
      %td= link_to 'Show', largesurvey
      %td= link_to 'Edit', edit_largesurvey_path(largesurvey)
      %td= link_to 'Destroy', largesurvey, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Largesurvey', new_largesurvey_path

app/views/largesurveys/new.html.haml
-unless @largesurvey.errors.empty?
	= %{Your changes can't be saved because #{controller_name} has the following errors}
	- @largesurvey.errors.full_messages.each do |error|
		%li= error
%div{:class=>'container header_div'}
	%div{:class => "container title_div"}
		
		%div{:class => " center_div"}
			%div{:class => " center_text_div"}

				.text-center
					.small
					%strong SURVEY 1 - "PRODUCT / SERVICE EXPERIENCES"
					
				%p
				In this research, we are interested in consumers' experiences with products and services.
				%p
				In the space below, please write a 
				%strong review of a restaurant experience 
				that took place 
				%strong at least one month ago but within the past year.
				%p
				Your review must contain 
				%ins between 135 to 145 words. 
				A word counter (below the text box) will indicate how many words you have written. You will not be able to submit your review unless it contains between 
				%ins 135-145 words.

%br
%br
%div{:class=>'col-md-6 col-md-offset-3'}
	= form_for @largesurvey do |f|
		= f.label :name, "Name of Restaurant:"
		%br
		%br

		= f.text_field :name, :size => "90x10"
		%br
		%br	
		%br

		= f.label :reviw, "Review of Restaurant:"
		%br
		%br

		= f.text_area :review, :size => "90x10"
		%br
		%div{:class=>'pull-right'}
			= f.submit "Submit"
%br
%br		
%div{:class=>'col-md-6 col-md-offset-3'}
	.text-center
		%h5
		%strong Word Counter:
	
	%div{:id =>"counter_div"}
		%span{:id =>"counter"}



:javascript
	
	 
	function pluralize_words(num) {
		if(num == 1) {
	  		return num + " word";
		} else {
	  	return num + " words";
		}
	}

	$("#largesurvey_review").keyup(function() {
		var regex = /\s+/gi;
		var chars = $("#largesurvey_review").val().trim().replace(regex, ' ').split(' ').length;
		
	  	$("#counter").text(" you have written " + pluralize_words(chars));
		
	});

app/views/largesurveys/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @largesurvey.name
%p
  %b Review:
  = @largesurvey.review

= link_to 'Edit', edit_largesurvey_path(@largesurvey)
\|
= link_to 'Back', largesurveys_path

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title=  "Welcome"
		= stylesheet_link_tag "application", :media =>"all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
	
	%div{:class => "container-fluid"}
		=yield

app/views/midsurveys/_form.html.haml
= form_for @midsurvey do |f|
  - if @midsurvey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@midsurvey.errors.count, "error")} prohibited this midsurvey from being saved:"
      %ul
        - @midsurvey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :review
    = f.text_field :review
  .actions
    = f.submit 'Save'

app/views/midsurveys/edit.html.haml
%h1 Editing midsurvey

= render 'form'

= link_to 'Show', @midsurvey
\|
= link_to 'Back', midsurveys_path

app/views/midsurveys/index.html.haml
%h3 All the surveys between 40-50 words 
%br
Download:
= link_to "CSV", midsurveys_path(format: "csv")
%br
%br

%table{:class => "table table-hover"}
  %tr
    %th Name
    %th Review
    %th
    %th
    %th

  - @midsurveys.each do |midsurvey|
    %tr
      %td= midsurvey.name
      %td= midsurvey.review
      %td= link_to 'Show', midsurvey
      %td= link_to 'Edit', edit_midsurvey_path(midsurvey)
      %td= link_to 'Destroy', midsurvey, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Midsurvey', new_midsurvey_path

app/views/midsurveys/new.html.haml
-unless @midsurvey.errors.empty?
	= %{Your changes can't be saved because #{controller_name} has the following errors}
	- @midsurvey.errors.full_messages.each do |error|
		%li= error
%div{:class=>'container header_div'}
	%div{:class => "container title_div"}
		
		%div{:class => " center_div"}
			%div{:class => " center_text_div"}

				.text-center
					.small
					%strong SURVEY 1 - "PRODUCT / SERVICE EXPERIENCES"
					
				%p
				In this research, we are interested in consumers' experiences with products and services.
				%p
				In the space below, please write a 
				%strong review of a restaurant experience 
				that took place 
				%strong at least one month ago but within the past year.
				%p
				Your review must contain 
				%ins between 40 to 50 words. 
				A word counter (below the text box) will indicate how many words you have written. You will not be able to submit your review unless it contains between 
				%ins 40-50 words.

%br
%br
%div{:class=>'col-md-6 col-md-offset-3'}
	= form_for @midsurvey do |f|
		= f.label :name, "Name of Restaurant:"
		%br
		%br

		= f.text_field :name, :size => "90x10"
		%br
		%br	
		%br

		= f.label :reviw, "Review of Restaurant:"
		%br
		%br

		= f.text_area :review, :size => "90x10"
		%br
		%div{:class=>'pull-right'}
			= f.submit "Submit"
%br
%br		
%div{:class=>'col-md-6 col-md-offset-3'}
	.text-center
		%h5
		%strong Word Counter:
	%br
	%div{:id =>"counter_div"}
		%span{:id =>"counter"}



:javascript
	
	 
	function pluralize_words(num) {
		if(num == 1) {
	  		return num + " word";
		} else {
	  	return num + " words";
		}
	}

	$("#midsurvey_review").keyup(function() {
		var regex = /\s+/gi;
		var chars = $("#midsurvey_review").val().trim().replace(regex, ' ').split(' ').length;
		
	  	$("#counter").text(" you have written " + pluralize_words(chars));
	});

app/views/midsurveys/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @midsurvey.name
%p
  %b Review:
  = @midsurvey.review

= link_to 'Edit', edit_midsurvey_path(@midsurvey)
\|
= link_to 'Back', midsurveys_path

app/views/smallsurveys/_form.html.haml
= form_for @smallsurvey do |f|
  - if @smallsurvey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@smallsurvey.errors.count, "error")} prohibited this smallsurvey from being saved:"
      %ul
        - @smallsurvey.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :review
    = f.text_field :review
  .actions
    = f.submit 'Save'

app/views/smallsurveys/edit.html.haml
%h1 Editing smallsurvey

= render 'form'

= link_to 'Show', @smallsurvey
\|
= link_to 'Back', smallsurveys_path

app/views/smallsurveys/index.html.haml
%h3 All the surveys between 10-20 words 
%br
Download:
= link_to "CSV", smallsurveys_path(format: "csv")
%br
%br

%table{:class => "table table-hover"}
  %tr
    %th Name
    %th Review
    %th
    %th
    %th

  - @smallsurveys.each do |smallsurvey|
    %tr
      %td= smallsurvey.name
      %td= smallsurvey.review
      %td= link_to 'Show', smallsurvey
      %td= link_to 'Edit', edit_smallsurvey_path(smallsurvey)
      %td= link_to 'Destroy', smallsurvey, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Smallsurvey', new_smallsurvey_path

app/views/smallsurveys/new.html.haml
-unless @smallsurvey.errors.empty?
	= %{Your changes can't be saved because #{controller_name} has the following errors}
	- @smallsurvey.errors.full_messages.each do |error|
		%li= error
%div{:class=>'container header_div'}
	%div{:class => "container title_div"}
		
		%div{:class => " center_div"}
			%div{:class => " center_text_div"}
				.text-center
					.small
					%strong SURVEY 1 - "PRODUCT / SERVICE EXPERIENCES"
					
				%p
				In this research, we are interested in consumers' experiences with products and services.
				%p
				In the space below, please write a 
				%strong review of a restaurant experience 
				that took place 
				%strong at least one month ago but within the past year.
				%p
				Your review must contain 
				%ins between 10 to 20 words. 
				A word counter (below the text box) will indicate how many words you have written. You will not be able to submit your review unless it contains between 
				%ins 10-20 words.

%br
%br
%div{:class=>'col-md-6 col-md-offset-3'}
	= form_for @smallsurvey do |f|
		= f.label :name, "Name of Restaurant:"
		%br
		%br

		= f.text_field :name, :size => "90x10"
		%br
		%br	
		%br

		= f.label :reviw, "Review of Restaurant:"
		%br
		%br

		= f.text_area :review, :size => "90x10"
		%br
		%div{:class=>'pull-right'}
			= f.submit "Submit"
%br
%br		
%div{:class=>'col-md-6 col-md-offset-3'}
	.text-center
		%h5
		%strong Word Counter:
	%div{:id =>"counter_div"}
		%span{:id =>"counter"}



:javascript
	
	 
	function pluralize_words(num) {
		if(num == 1) {
	  		return num + " word";
		} else {
	  	return num + " words";
		}
	}

	$("#smallsurvey_review").keyup(function() {
		var regex = /\s+/gi;
		var chars = $("#smallsurvey_review").val().trim().replace(regex, ' ').split(' ').length;
		
		
	  	$("#counter").text(" you have written " + pluralize_words(chars))
	});

app/views/smallsurveys/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @smallsurvey.name
%p
  %b Review:
  = @smallsurvey.review

= link_to 'Edit', edit_smallsurvey_path(@smallsurvey)
\|
= link_to 'Back', smallsurveys_path